### PR TITLE
Create navbar

### PR DESCRIPTION
**Pull request by AmirNaghibi**
# Updating Website Header
### Desktop View

Screen Shot 2021-10-11 at 10 12 44 PM

### Mobile View

Screen Shot 2021-10-11 at 10 16 08 PM

Screen Shot 2021-10-11 at 10 16 21 PM

🔻 Note: **_Subscribe here_** link in https://bitsg.acm.org/events will go to a page where permission is needed. The link needs to be updated. (created an issue: #74 )

Screen Shot 2021-10-11 at 10 19 05 PM

Addressing Issue: #68

### CODE REVIEW

**Comment by Devesh21700Kumar** [comment]
> # Updating Website Header
> ### Desktop View
> Screen Shot 2021-10-11 at 10 12 44 PM
> 
> ### Mobile View
> Screen Shot 2021-10-11 at 10 16 08 PM
> 
> Screen Shot 2021-10-11 at 10 16 21 PM
> 
> 🔻 Note: **_Subscribe here_** link in https://bitsg.acm.org/events will go to a page where permission is needed. The link needs to be updated. (created an issue: #74 )
> 
> Screen Shot 2021-10-11 at 10 19 05 PM
> 
> Addressing Issue: #68

The PR looks good to me. Great work and thanks !!

1).I do feel that here
image
This subscribe to news letter could have been be centered a bit more.


2).Regarding the  wiki link , its opening without any 404 errors.

3).And as far as issue #74  is concerned, the form presently is made available to only our university students. Maybe that's why its asking you for permission.

**Comment by AmirNaghibi** [comment]
Thank you for the feedback. I'll look into it and update the PR soon :)

**Comment by AmirNaghibi** [comment]
Thanks for the reminder.
Unfortunately, I won't be able to work on this anymore due to other priorities.

Feel free to make the issue open again. The change should be minimal as most of the header features is in the PR.

**Comment by Aviral09** [comment]
No worries. Closing PR.

**Pull request closed without merging**
